-- Generated by drizzle-kit, with the comments below added by hand. Regenerating
-- it produces the same six statements in the same order; only the prose is new.
--
-- Three unrelated changes travel together because they were one unit of work:
--
-- 1. `share_created` and `share_viewed` (spec section 44.1, ADR-15). Both are
--    appended to the end of `attribution_event_type`. `ALTER TYPE … ADD VALUE`
--    is the only non-rewriting way to extend an enum, and it appends — which
--    is why `enums.ts` declares them last rather than next to `share_to_signup`
--    where they would read better. PostgreSQL 12 and later allow this inside a
--    transaction as long as the new value is not *used* in the same
--    transaction; nothing below uses one.
--
-- 2. `companies.industry_description` and `companies.services_offered`, the two
--    remaining fields of the «virksomhetsprofil» in spec sections 7.1 and 9.1.
--    Both nullable: section 9.1 fills them in during onboarding, and an account
--    that exists before onboarding completes must still be a valid row.
--
-- 3. The webhook idempotency key becomes `(postmark_message_id, event_type)`,
--    dropping `occurred_at`. See the comment on `emailEvents` in
--    `src/schema/notifications.ts`: with `occurred_at` in the key, a Postmark
--    redelivery carrying a timestamp that differed at all would have inserted a
--    second row and re-run the suppression side effects, which is precisely
--    what spec section 27's "idempotent behandling" exists to prevent.

ALTER TYPE "public"."attribution_event_type" ADD VALUE 'share_created';--> statement-breakpoint
ALTER TYPE "public"."attribution_event_type" ADD VALUE 'share_viewed';--> statement-breakpoint
DROP INDEX "email_events_message_type_occurred_key";--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "industry_description" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "services_offered" text;--> statement-breakpoint
CREATE UNIQUE INDEX "email_events_message_id_event_type_key" ON "email_events" USING btree ("postmark_message_id","event_type");
