import { timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Column builders shared by every table.
 *
 * The point of this file is that no table can accidentally get a naive
 * timestamp. Spec section 11 stores a per-profile IANA timezone and the digest
 * job resolves local send times against it; a `timestamp without time zone`
 * anywhere in that chain silently reinterprets an instant as whatever the
 * server's TimeZone setting happens to be, and the bug only shows up twice a
 * year when Norway changes offset. Every temporal column below is
 * `timestamp with time zone`.
 */

/** `timestamptz`, mapped to a JavaScript `Date`. */
export function timestamptz(name: string) {
  return timestamp(name, { withTimezone: true, mode: 'date' });
}

/** A UUID primary key generated by the database. */
export function primaryId() {
  return uuid('id').primaryKey().defaultRandom();
}

export function createdAt() {
  return timestamptz('created_at').notNull().defaultNow();
}

/**
 * `updated_at` defaults to now on insert. It is the application's job to set it
 * on update: there is deliberately no trigger, because a trigger would also
 * fire for the consent-severing update in ADR-0009 and for backfills, and a
 * timestamp that moves for reasons nobody asked for is worse than one that has
 * to be written explicitly.
 */
export function updatedAt() {
  return timestamptz('updated_at').notNull().defaultNow();
}
